CREATE TABLE ADVENTURE_TRIP (
    TRIP_ID DECIMAL(3) NOT NULL,
    TRIP_NAME VARCHAR(75),       -- Changed from CHAR to VARCHAR
    START_LOCATION CHAR(50),
    STATE CHAR(2),
    DISTANCE NUMBER(4),          -- Changed from DECIMAL to NUMBER
    MAX_GRP_SIZE NUMBER(4),      -- Changed from DECIMAL to NUMBER
    TYPE CHAR(20),
    SEASON CHAR(20),
    PRIMARY KEY (TRIP_ID)
);
